# Generated by Django 3.2.16 on 2024-06-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leavemanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='leave_letter',
        ),
    ]
